/*
 * Esse cabeçalho vai ser utilizado na herança para todas as telas
 */
package Telas;

public class Cabecalho extends javax.swing.JFrame {

    public Cabecalho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCabecalho = new javax.swing.JPanel();
        jLabelSLI = new javax.swing.JLabel();
        jLabelNomeImob = new javax.swing.JLabel();
        jLabelHoraAtual = new javax.swing.JLabel();
        jLabelDataAtual = new javax.swing.JLabel();
        jLabelNomeCidade = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Aluguel de Imoveis");

        jLabelSLI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSLI.setForeground(new java.awt.Color(0, 0, 51));
        jLabelSLI.setText("SLI");

        jLabelNomeImob.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNomeImob.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNomeImob.setText("Imobiliaria Vida Boa");

        jLabelHoraAtual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelHoraAtual.setText("Hora:");

        jLabelDataAtual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDataAtual.setText("Data:");

        jLabelNomeCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNomeCidade.setText("Ponta Grossa/Pr");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanelCabecalhoLayout = new javax.swing.GroupLayout(jPanelCabecalho);
        jPanelCabecalho.setLayout(jPanelCabecalhoLayout);
        jPanelCabecalhoLayout.setHorizontalGroup(
            jPanelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabecalhoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelNomeImob, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 552, Short.MAX_VALUE)
                .addComponent(jLabelSLI, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeCidade)
                    .addComponent(jLabelDataAtual)
                    .addComponent(jLabelHoraAtual))
                .addContainerGap())
        );
        jPanelCabecalhoLayout.setVerticalGroup(
            jPanelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelCabecalhoLayout.createSequentialGroup()
                            .addComponent(jLabelDataAtual)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelHoraAtual)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelNomeCidade)))
                    .addGroup(jPanelCabecalhoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSLI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNomeImob, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCabecalho, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDataAtual;
    private javax.swing.JLabel jLabelHoraAtual;
    private javax.swing.JLabel jLabelNomeCidade;
    private javax.swing.JLabel jLabelNomeImob;
    private javax.swing.JLabel jLabelSLI;
    private javax.swing.JPanel jPanelCabecalho;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
