/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.ImovelDAO;
import Modelo.Imovel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.Visibility;
import javax.swing.JOptionPane;

/**
 *
 * @author klebe
 */
public class TelaCadImovel extends javax.swing.JFrame {

    private int id;
    private boolean vrUpDel;//PARA UTILIZAR NO BOTAO SALVAR: TRUE E NOVO IMOVEL, FALSE É ATUALIZAR IMOVEL
    
    public TelaCadImovel() {
        initComponents();
        vrUpDel = true;
    }
    /*
        Ordem das colunas no jTableDisponivel
       0 ID	Object	true	false
       1 Rua	Object	true	false
       2 N°	Object	true	false
       3 Bairro	Object	true	false
       4 Cidade	Object	true	false
       5 CEP	Object	true	false
       6 Tipo	Object	true	false
       7 Quartos	Object	true	false
       8 m²	Object	true	false
       9 Valor	Object	true	true
       10 Observação	Object	true	false
        */
    public TelaCadImovel(Imovel imv) {//construtor utilizado no update
        initComponents();
        //ImovelDAO imvDao = new ImovelDAO();
        id = imv.getId();
        jTextFielRua.setText(imv.getRua());
        jTextFieldNumero.setText(Integer.toString(imv.getNumero()));//convertendo para String
        jTextFielBairro.setText(imv.getBairro());
        jTextFielCidade.setText(imv.getCidade());
        jTextFielCep.setText(imv.getCEP());
        jTextFielTipo.setText(imv.getTipo());
        jTextFielQtdQuartos.setText(Integer.toString(imv.getQtdQuarto()));
        jTextFielTamanho.setText(Double.toString(imv.getTamanho()));
        jTextFielValor.setText(Double.toString(imv.getValor()));
        jTextFielObs.setText(imv.getObs());
        
        vrUpDel = false;
    }
      
    public void mostraTela(){
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCaracImovel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonSalvarImovel = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();
        jTextFielTamanho = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFielQtdQuartos = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFielTipo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFielValor = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFielObs = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JToggleButton();
        jPanelEndereco = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextFielCep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFielRua = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFielBairro = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFielCidade = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFielEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSalvarImovel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonSalvarImovel.setText("Salvar");
        jButtonSalvarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarImovelActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel19.setText("m²");

        jTextFielTamanho.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFielTamanho.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielTamanhoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel20.setText("Qtd Quartos:");

        jTextFielQtdQuartos.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFielQtdQuartos.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielQtdQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielQtdQuartosActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel21.setText("Tamanho:");

        jTextFielTipo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFielTipo.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielTipoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel17.setText("Tipo:");

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel18.setText("Informações do Imóvel:");

        jTextFielValor.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFielValor.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielValorActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel26.setText("Valor do Aluguel:");

        jLabel27.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel27.setText("Observação:");

        jTextFielObs.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFielObs.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielObsActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel28.setText("Precisa fazer as verificações de int String para nao dar erro ");

        jLabel29.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel29.setText("Para testar digite numero em todos os campos e depois clique em salvar");

        jButtonCancelar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCaracImovelLayout = new javax.swing.GroupLayout(jPanelCaracImovel);
        jPanelCaracImovel.setLayout(jPanelCaracImovelLayout);
        jPanelCaracImovelLayout.setHorizontalGroup(
            jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaracImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelCaracImovelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielQtdQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCaracImovelLayout.createSequentialGroup()
                        .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvarImovel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar))
                    .addComponent(jTextFielObs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCaracImovelLayout.createSequentialGroup()
                        .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel27)
                            .addGroup(jPanelCaracImovelLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFielValor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCaracImovelLayout.setVerticalGroup(
            jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaracImovelLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFielTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFielQtdQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFielObs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCaracImovelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29))
                    .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSalvarImovel)
                        .addComponent(jButtonCancelar)))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanelCaracImovel, java.awt.BorderLayout.PAGE_END);

        jLabel22.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel22.setText("Endereço:");

        jTextFielCep.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFielCep.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielCepActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel12.setText("Rua:");

        jTextFielRua.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFielRua.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielRuaActionPerformed(evt);
            }
        });

        jTextFieldNumero.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFieldNumero.setForeground(new java.awt.Color(0, 0, 51));
        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel14.setText("Numero:");

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel11.setText("CEP:");

        jLabel23.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel23.setText("Bairro:");

        jTextFielBairro.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFielBairro.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielBairroActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel24.setText("Cidade:");

        jTextFielCidade.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFielCidade.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielCidadeActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel25.setText("Estado:");

        jTextFielEstado.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTextFielEstado.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFielCep, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielRua)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFielEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextFielCep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jTextFielEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFielCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelEndereco, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFielCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielCepActionPerformed

    }//GEN-LAST:event_jTextFielCepActionPerformed

    private void jTextFielRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielRuaActionPerformed

    private void jButtonSalvarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarImovelActionPerformed
        //quando acionado o botão Salvar ele captura as informações dos campos e adiciona no banco        
        Imovel imv = new Imovel();
        ImovelDAO imvDao = new ImovelDAO();
        imv.setId(id);
        imv.setCEP(jTextFielCep.getText());
        imv.setRua(jTextFielRua.getText());
        imv.setBairro(jTextFielBairro.getText());
        imv.setCidade(jTextFielCidade.getText());
        imv.setEstado(jTextFielEstado.getText());
        imv.setTipo(jTextFielTipo.getText());
        imv.setObs(jTextFielObs.getText());
        
        //COLOCAR DENTRO DE UM TRY CATCH PARA VERIFICAR SE FOI COLOCADO NUMERO
            imv.setValor(Double.parseDouble(jTextFielValor.getText()));
            imv.setTamanho(Double.parseDouble(jTextFielTamanho.getText()));
            imv.setNumero(Integer.parseInt(jTextFieldNumero.getText()));//fazer um if verificando se é numero
            imv.setQtdQuarto(Integer.parseInt(jTextFielQtdQuartos.getText()));
            
        //verificar se é para criar ou atualizar
        if(vrUpDel){
            imvDao.create(imv);
        } else {
            imvDao.update(imv);
        }
        dispose();
        TelaInicial tInicial = new TelaInicial();
        tInicial.setVisible(true);
    }//GEN-LAST:event_jButtonSalvarImovelActionPerformed

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void jTextFielTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielTipoActionPerformed

    private void jTextFielTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielTamanhoActionPerformed

    private void jTextFielQtdQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielQtdQuartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielQtdQuartosActionPerformed

    private void jTextFielBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielBairroActionPerformed

    private void jTextFielCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielCidadeActionPerformed

    private void jTextFielEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielEstadoActionPerformed

    private void jTextFielValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielValorActionPerformed

    private void jTextFielObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielObsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielObsActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
        TelaInicial tInicial = new TelaInicial();
        tInicial.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonCancelar;
    private javax.swing.JToggleButton jButtonSalvarImovel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanelCaracImovel;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFielBairro;
    private javax.swing.JTextField jTextFielCep;
    private javax.swing.JTextField jTextFielCidade;
    private javax.swing.JTextField jTextFielEstado;
    private javax.swing.JTextField jTextFielObs;
    private javax.swing.JTextField jTextFielQtdQuartos;
    private javax.swing.JTextField jTextFielRua;
    private javax.swing.JTextField jTextFielTamanho;
    private javax.swing.JTextField jTextFielTipo;
    private javax.swing.JTextField jTextFielValor;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
