/*
 * TELA INICIAL

 */
package Telas;

import Controle.ImovelDAO;
import Modelo.Imovel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;

public final class TelaInicial extends Cabecalho {
    
    //private TelaCadLocacao TCadLocacao = new TelaCadLocacao();
    //private TelaCadImovel TCadImovel = new TelaCadImovel();
    private int id;
    
    public TelaInicial() {
        initComponents();
        PreencheTableDisponiveis();
        PreencheTableLocado();
    }
    
    private Controle.ImovelDAO imovel;
    
    public void PreencheTableDisponiveis(){
        DefaultTableModel modelo = (DefaultTableModel) jTableDisponivel.getModel();
        
        modelo.setNumRows(0);//limpa as linhas para nao aparecer duplicado
        
        ImovelDAO imvDao = new ImovelDAO();
        
        imvDao.listaImovelDisponivel().stream().forEach((i) -> {
            modelo.addRow(new Object[]{
                 i.getId(),
                 i.getRua(),
                 i.getNumero(),
                 i.getBairro(),
                 i.getCidade(),
                 i.getCEP(),
                 i.getTipo(),
                 i.getQtdQuarto(),
                 i.getTamanho(),
                 i.getValor(),
                 i.getObs()
            });
        });
    }
    public void PreencheTableLocado(){
        DefaultTableModel modelo = (DefaultTableModel) jTableLocado.getModel();
        
        modelo.setNumRows(0);//limpa as linhas para nao aparecer duplicado
        
        ImovelDAO imvDao = new ImovelDAO();
        
        imvDao.listaImovelLocado().stream().forEach((i) -> {
            modelo.addRow(new Object[]{
                 i.getId(),
                 i.getRua(),
                 i.getNumero(),
                 i.getBairro(),
                 i.getCidade(),
                 i.getCEP(),
                 i.getTipo(),
                 i.getQtdQuarto(),
                 i.getTamanho(),
                 i.getValor(),
                 i.getObs()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPaneInicial = new javax.swing.JTabbedPane();
        jPanelDisponivel = new javax.swing.JPanel();
        jPanelRodapeDisponiveis = new javax.swing.JPanel();
        jButtonInformarLocacao = new javax.swing.JToggleButton();
        jButtonInserir = new javax.swing.JToggleButton();
        jButtonAlterar = new javax.swing.JToggleButton();
        jButtonExcluir = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDisponivel = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanelLocado = new javax.swing.JPanel();
        jPanelRodapeLocado = new javax.swing.JPanel();
        jButtonAlterarLocacao = new javax.swing.JToggleButton();
        jButtonFinalizar = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableLocado = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Aluguel de Imoveis");

        jTabbedPaneInicial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPaneInicial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButtonInformarLocacao.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonInformarLocacao.setText("Informar Locação");
        jButtonInformarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformarLocacaoActionPerformed(evt);
            }
        });

        jButtonInserir.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonInserir.setText("Novo");
        jButtonInserir.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButtonInserirAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        jButtonAlterar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRodapeDisponiveisLayout = new javax.swing.GroupLayout(jPanelRodapeDisponiveis);
        jPanelRodapeDisponiveis.setLayout(jPanelRodapeDisponiveisLayout);
        jPanelRodapeDisponiveisLayout.setHorizontalGroup(
            jPanelRodapeDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRodapeDisponiveisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonInformarLocacao)
                .addGap(30, 30, 30))
        );
        jPanelRodapeDisponiveisLayout.setVerticalGroup(
            jPanelRodapeDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodapeDisponiveisLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelRodapeDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInformarLocacao)
                    .addComponent(jButtonInserir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTableDisponivel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Rua", "N°", "Bairro", "Cidade", "CEP", "Tipo", "Quartos", "m²", "Valor", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableDisponivel);
        if (jTableDisponivel.getColumnModel().getColumnCount() > 0) {
            jTableDisponivel.getColumnModel().getColumn(0).setPreferredWidth(8);
            jTableDisponivel.getColumnModel().getColumn(2).setPreferredWidth(11);
            jTableDisponivel.getColumnModel().getColumn(5).setPreferredWidth(28);
            jTableDisponivel.getColumnModel().getColumn(7).setPreferredWidth(21);
            jTableDisponivel.getColumnModel().getColumn(8).setPreferredWidth(18);
            jTableDisponivel.getColumnModel().getColumn(9).setPreferredWidth(22);
        }

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel5.setText("Botões novo, alterar e excluir se referem a tabela Imovel do banco de dados");

        javax.swing.GroupLayout jPanelDisponivelLayout = new javax.swing.GroupLayout(jPanelDisponivel);
        jPanelDisponivel.setLayout(jPanelDisponivelLayout);
        jPanelDisponivelLayout.setHorizontalGroup(
            jPanelDisponivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRodapeDisponiveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDisponivelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(jPanelDisponivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDisponivelLayout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelDisponivelLayout.setVerticalGroup(
            jPanelDisponivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisponivelLayout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(47, 47, 47)
                .addComponent(jPanelRodapeDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelDisponivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDisponivelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(174, Short.MAX_VALUE)))
        );

        jTabbedPaneInicial.addTab("Imóveis Disponíveis", jPanelDisponivel);

        jButtonAlterarLocacao.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonAlterarLocacao.setText("Alterar Locação");
        jButtonAlterarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarLocacaoActionPerformed(evt);
            }
        });

        jButtonFinalizar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonFinalizar.setText("Encerrar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRodapeLocadoLayout = new javax.swing.GroupLayout(jPanelRodapeLocado);
        jPanelRodapeLocado.setLayout(jPanelRodapeLocadoLayout);
        jPanelRodapeLocadoLayout.setHorizontalGroup(
            jPanelRodapeLocadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRodapeLocadoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButtonFinalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAlterarLocacao)
                .addGap(30, 30, 30))
        );
        jPanelRodapeLocadoLayout.setVerticalGroup(
            jPanelRodapeLocadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodapeLocadoLayout.createSequentialGroup()
                .addGroup(jPanelRodapeLocadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRodapeLocadoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonAlterarLocacao))
                    .addGroup(jPanelRodapeLocadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonFinalizar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTableLocado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Rua", "N°", "Bairro", "Cidade", "CEP", "Tipo", "Quartos", "m²", "Valor", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableLocado);
        if (jTableLocado.getColumnModel().getColumnCount() > 0) {
            jTableLocado.getColumnModel().getColumn(0).setPreferredWidth(8);
            jTableLocado.getColumnModel().getColumn(2).setPreferredWidth(11);
            jTableLocado.getColumnModel().getColumn(5).setPreferredWidth(28);
            jTableLocado.getColumnModel().getColumn(7).setPreferredWidth(21);
            jTableLocado.getColumnModel().getColumn(8).setPreferredWidth(18);
            jTableLocado.getColumnModel().getColumn(9).setPreferredWidth(22);
        }

        javax.swing.GroupLayout jPanelLocadoLayout = new javax.swing.GroupLayout(jPanelLocado);
        jPanelLocado.setLayout(jPanelLocadoLayout);
        jPanelLocadoLayout.setHorizontalGroup(
            jPanelLocadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRodapeLocado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelLocadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLocadoLayout.setVerticalGroup(
            jPanelLocadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocadoLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jPanelRodapeLocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPaneInicial.addTab("Imóveis Locados", jPanelLocado);

        getContentPane().add(jTabbedPaneInicial, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarLocacaoActionPerformed

    private void jButtonInformarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformarLocacaoActionPerformed
        //ELE TEM QUE ABRIR A TELA CADASTRO COM OS CAMPOS PREENCHIDOS
        Imovel imv = new Imovel();
        /*d
        Ordem das colunas no jTableDisponivel
       0 ID	Object	true	false
       1 Rua	Object	true	false
       2 N°	Object	true	false
       3 Bairro	Object	true	false
       4 Cidade	Object	true	false
       5 CEP	Object	true	false
       6 Tipo	Object	true	false
       7 Quartos	Object	true	false
       8 m²	Object	true	false
       9 Valor	Object	true	true
       10 Observação	Object	true	false
        */
        if (jTableDisponivel.getSelectedRow() != -1) {
             imv.setId((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 0));
            imv.setRua(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 1).toString());
            imv.setNumero((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 2));
            imv.setBairro(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 3).toString());
            imv.setCidade(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 4).toString());
            imv.setCEP(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 5).toString());
            imv.setTipo(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 6).toString());
            imv.setQtdQuarto((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 7));
            imv.setTamanho((double) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 8));
            imv.setValor((double) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 9));
            imv.setObs(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 10).toString());
            
            //ImovelDAO dao = new ImovelDAO();
            TelaCadLocacao loc = new TelaCadLocacao(imv);
            
            dispose();
            loc.setVisible(true);
        }
            
            
            
    }//GEN-LAST:event_jButtonInformarLocacaoActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        TelaCadImovel TCadImovel = new TelaCadImovel();
        TCadImovel.setVisible(true);
        PreencheTableDisponiveis();
    }//GEN-LAST:event_jButtonInserirActionPerformed
private boolean vr;
    
    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        //ELE TEM QUE ABRIR A TELA CADASTRO COM OS CAMPOS PREENCHIDOS
        Imovel imv = new Imovel();
        /*
        Ordem das colunas no jTableDisponivel
       0 ID	Object	true	false
       1 Rua	Object	true	false
       2 N°	Object	true	false
       3 Bairro	Object	true	false
       4 Cidade	Object	true	false
       5 CEP	Object	true	false
       6 Tipo	Object	true	false
       7 Quartos	Object	true	false
       8 m²	Object	true	false
       9 Valor	Object	true	true
       10 Observação	Object	true	false
        */
        if (jTableDisponivel.getSelectedRow() != -1) {
             imv.setId((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 0));
            imv.setRua(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 1).toString());
            imv.setNumero((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 2));
            imv.setBairro(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 3).toString());
            imv.setCidade(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 4).toString());
            imv.setCEP(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 5).toString());
            imv.setTipo(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 6).toString());
            imv.setQtdQuarto((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 7));
            imv.setTamanho((double) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 8));
            imv.setValor((double) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 9));
            imv.setObs(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 10).toString());
            
            ImovelDAO dao = new ImovelDAO();
            TelaCadImovel TCadImovelAlterar = new TelaCadImovel(imv);

            TCadImovelAlterar.mostraTela();
            dispose();
            //TCadImovelAlterar.setVisible(true);

        }
        
      
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTableDisponivel.getSelectedRow() != -1) {

            Imovel i = new Imovel();
            ImovelDAO dao = new ImovelDAO();

            i.setId((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 0));
            
            dao.delete(i);
            PreencheTableDisponiveis();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }


    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonInserirAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButtonInserirAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInserirAncestorAdded

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonAlterar;
    private javax.swing.JToggleButton jButtonAlterarLocacao;
    private javax.swing.JToggleButton jButtonExcluir;
    private javax.swing.JToggleButton jButtonFinalizar;
    private javax.swing.JToggleButton jButtonInformarLocacao;
    private javax.swing.JToggleButton jButtonInserir;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelDisponivel;
    private javax.swing.JPanel jPanelLocado;
    private javax.swing.JPanel jPanelRodapeDisponiveis;
    private javax.swing.JPanel jPanelRodapeLocado;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPaneInicial;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDisponivel;
    private javax.swing.JTable jTableLocado;
    // End of variables declaration//GEN-END:variables
}
